---
title: "Indicator Normalizations"
output: html_document
date: "2022-11-09"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
library(janitor)
```

# Surf Spots

```{r}
ws_sl_surf <- read_csv(here("data", "ws_sl.csv")) %>% 
  clean_names()
```

```{r}
ws_sl_surf_na <- ws_sl_surf %>% 
  mutate(quality = case_when(
    quality == 0.0 ~ ,
    quality == 5.0 ~ "5.0",
    quality == 4.0 ~ "4.0",
    quality == 3.5 ~ "3.5",
    quality == 3.0 ~ "3.0",
    quality == 2.0 ~ "2.0"
  )) %>% 
  mutate(frequency = case_when(
    frequency == 0 ~ "NA",
    frequency == 5 ~ "5",
    frequency == 4 ~ "4",
    frequency == 3 ~ "3",
    frequency == 2 ~ "2",
    frequency == 1 ~ "1"
  ))

ws_sl_surf_na %>% 
  as.integer(frequency) %>% 
  as.integer(quality)
```

## Surf Spots Export

```{r}
write_csv(ws_sl_surf_na, file = "ws_sl_sys_spots.csv")
```

# Pressure Index

# Social Index

## Biodiversity Sub Index

## Surf Subindex

```{r}
# read in data
surf_indicators <- read_csv(here("data", "surf_indicators.csv")) %>% 
  select(-OBJECTID) %>% 
  clean_names()
```

### Surf Clusters

```{r}
max_cluster <- max(surf_indicators$join_count)
min_cluster <- min(surf_indicators$join_count)

cluster_normalized <- round((surf_indicators$join_count - min_cluster) / (max_cluster - min_cluster), 6)

surf_indicators$normalized_cluster <- cluster_normalized
```

### Direction

```{r}
surf_indicators$normalized_direction <- surf_indicators$numerical_direction
```

### Frequency

```{r}
max_frequency <- max(surf_indicators$numerical_frequency)
min_frequency <- min(surf_indicators$numerical_frequency)

frequency_normalized <- round((surf_indicators$numerical_frequency - min_frequency) / (max_frequency - min_frequency), 10)

surf_indicators$normalized_frequency <- frequency_normalized
```

### Experience

```{r}
surf_indicators$normalized_experience <- surf_indicators$numerical_experience
```

### Quality

```{r}
max_quality <- max(surf_indicators$numerical_quality)
min_quality <- min(surf_indicators$numerical_quality)

quality_normalized <- round((surf_indicators$numerical_quality - min_quality) / (max_quality - min_quality), 10)

surf_indicators$normalized_quality <- quality_normalized
```

## Surf Subindex Normalized

```{r}
normalized_added_indicators <- round(surf_indicators$normalized_quality + surf_indicators$normalized_experience + surf_indicators$normalized_frequency + surf_indicators$normalized_direction + surf_indicators$normalized_cluster, 10)

surf_indicators$added_normalized <- normalized_added_indicators

max_added <- max(surf_indicators$added_normalized)
min_added <- min(surf_indicators$added_normalized)

surf_normalized <- round((surf_indicators$added_normalized - min_added) / (max_added - min_added), 10)

surf_indicators$surf_subindex <- surf_normalized
```

```{r}
## Surf Subindex Indicators Export
# write_csv(surf_indicators, "surf_indicators_normalized.csv")
```

## Surf Subindex Export

```{r}
write_csv(surf_indicators, file = "surf_subindex.csv")
```

## Social Subindex

# Response Index



















