---
title: "Results Visualization"
author: "Kort Alexander"
date: "2023-02-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
library(cowplot)
```

# Data input and wrangling

```{r}
surf_spots <- read_csv(here("data", "surf_spot_states", "surf_spot_states.csv"))
sci_w_climate_10km <- read_csv(here("sci_w_climate.csv")) %>% 
  select(id, sci) %>% 
  mutate(sci_10km = sci) %>% 
  select(-sci)
sci_wo_climate_10km <- read_csv(here("sci_wo_climate.csv")) %>% 
  select(id, sci) %>% 
  mutate(sci_wo_climate = sci) %>% 
  select(-sci)
sci_w_climate_5km <- read_csv(here("sci_w_climate_5km.csv")) %>% 
  select(id, sci) %>% 
  mutate(sci_5km = sci) %>% 
  select(-sci)
sci_w_climate_1km <- read_csv(here("sci_w_climate_1km.csv")) %>% 
  select(id, sci) %>% 
  mutate(sci_1km = sci) %>% 
  select(-sci)

# join sci to surf spots using id
surf_spots <- left_join(surf_spots, sci_w_climate_10km, by = "id", keep = FALSE) %>% 
  left_join(sci_w_climate_5km, by = "id", keep = FALSE) %>% 
  left_join(sci_w_climate_1km, by = "id", keep = FALSE) %>% 
  left_join(sci_wo_climate_10km, by = "id", keep = FALSE)

# read in normalized climate results
normalized_climate <- read_csv(here("normalized_climate.csv"))

# join to surf spots
surf_spots <- surf_spots %>% 
  left_join(normalized_climate, by = "id", keep = FALSE)

# read in difference data
sci_diff <- read_csv(here("data", "sci_difference.csv")) %>% 
  select(id, difference)

# join to surf spots
surf_spots <- surf_spots %>% 
  left_join(sci_diff, by = "id", keep = FALSE)

# filter for each region
surf_spots_nne <- surf_spots %>% 
  filter(region == "Norte" | region == "Nordeste")
surf_spots_se <- surf_spots %>% 
  filter(region == "Sudeste")
surf_spots_s <- surf_spots %>% 
  filter(region == "Sul")
```

# Distribution of priority

```{r}
# calculate mean priority for different size buffers
mean_priority_10km_w_clim <- mean(surf_spots$sci_10km)
mean_priority_10km_wo_clim <- mean(surf_spots$sci_wo_climate)
mean_priority_5km <- mean(surf_spots$sci_5km)
mean_priority_1km <- mean(surf_spots$sci_1km)

# make histograms for all of Brazil and each region
hist_w_clim <- ggplot(data = surf_spots, aes(x = sci_10km)) +
  geom_histogram(breaks = c(0, 0.125, 0.25, 0.375, 0.5, 0.625, 0.75, 0.875, 1), fill = c("#d7191c", "#d7191c", "#fdae61", "#fdae61", "#a6d96a", "#a6d96a", "#1a9641", "#1a9641"), col = "black") +
  labs(x = "SCI with Climate", y = "Number of breaks") +
  scale_y_continuous(limits = c(0, 185)) +
  theme_minimal()
hist_wo_clim <- ggplot(data = surf_spots, aes(x = sci_wo_climate)) +
  geom_histogram(breaks = c(0, 0.125, 0.25, 0.375, 0.5, 0.625, 0.75, 0.875, 1), fill = c("#d7191c", "#d7191c", "#fdae61", "#fdae61", "#a6d96a", "#a6d96a", "#1a9641", "#1a9641"), col = "black") +
  labs(x = "SCI without Climate", y = "Number of breaks") +
  scale_y_continuous(limits = c(0, 185)) +
  theme_minimal()
hist_5km <- ggplot(data = surf_spots, aes(x = sci_5km)) +
  geom_histogram(breaks = c(0, 0.125, 0.25, 0.375, 0.5, 0.625, 0.75, 0.875, 1), fill = c("#d7191c", "#d7191c", "#fdae61", "#fdae61", "#a6d96a", "#a6d96a", "#1a9641", "#1a9641"), col = "black") +
  labs(x = "SCI with Climate (5 km)", y = "Number of breaks") +
  scale_y_continuous(limits = c(0, 185)) +
  geom_vline(xintercept = mean_priority_5km, linetype = 2) +
  theme_minimal()
hist_1km <- ggplot(data = surf_spots, aes(x = sci_1km)) +
  geom_histogram(breaks = c(0, 0.125, 0.25, 0.375, 0.5, 0.625, 0.75, 0.875, 1), fill = c("#d7191c", "#d7191c", "#fdae61", "#fdae61", "#a6d96a", "#a6d96a", "#1a9641", "#1a9641"), col = "black") +
  labs(x = "SCI with Climate (1 km)", y = "Number of breaks") +
  scale_y_continuous(limits = c(0, 185)) +
  geom_vline(xintercept = mean_priority_1km, linetype = 2) +
  theme_minimal()

mean_priority_nne_w_clim <- mean(surf_spots_nne$sci_10km)
mean_priority_se_w_clim <- mean(surf_spots_se$sci_10km)
mean_priority_s_w_clim <- mean(surf_spots_s$sci_10km)

mean_priority_nne_wo_clim <- mean(surf_spots_nne$sci_wo_climate)
mean_priority_se_wo_clim <- mean(surf_spots_se$sci_wo_climate)
mean_priority_s_wo_clim <- mean(surf_spots_s$sci_wo_climate)

hist_nne_w_clim <- ggplot(data = surf_spots_nne, aes(x = sci_10km)) +
  geom_histogram(breaks = c(0, 0.125, 0.25, 0.375, 0.5, 0.625, 0.75, 0.875, 1), fill = c("#d7191c", "#d7191c", "#fdae61", "#fdae61", "#a6d96a", "#a6d96a", "#1a9641", "#1a9641"), col = "black") +
  scale_y_continuous(limits = c(0, 60)) +
  geom_vline(xintercept = mean_priority_nne_w_clim, linetype = 2) +
  labs(x = "SCI with Climate", y = "Number of breaks", title = "North/Northeast") +
  theme_minimal() +
  theme(text = element_text(size = 18), plot.background = element_rect(colour = "#FFBEBE", fill=NA, size=5))
hist_se_w_clim <- ggplot(data = surf_spots_se, aes(x = sci_10km)) +
  geom_histogram(breaks = c(0, 0.125, 0.25, 0.375, 0.5, 0.625, 0.75, 0.875, 1), fill = c("#d7191c", "#d7191c", "#fdae61", "#fdae61", "#a6d96a", "#a6d96a", "#1a9641", "#1a9641"), col = "black") +
  scale_y_continuous(limits = c(0, 60)) +
  geom_vline(xintercept = mean_priority_se_w_clim, linetype = 2) +
  labs(x = "SCI with Climate", y = "Number of breaks", title = "Southeast") +
  theme_minimal() +
  theme(text = element_text(size = 18), plot.background = element_rect(colour = "#E8BEFF", fill=NA, size=5))
hist_s_w_clim <- ggplot(data = surf_spots_s, aes(x = sci_10km)) +
  geom_histogram(breaks = c(0, 0.125, 0.25, 0.375, 0.5, 0.625, 0.75, 0.875, 1), fill = c("#d7191c", "#d7191c", "#fdae61", "#fdae61", "#a6d96a", "#a6d96a", "#1a9641", "#1a9641"), col = "black") +
  scale_y_continuous(limits = c(0, 60)) +
  geom_vline(xintercept = mean_priority_s_w_clim, linetype = 2) +
  labs(x = "SCI with Climate", y = "Number of breaks", title = "South") +
  theme_minimal() +
  theme(text = element_text(size = 18), plot.background = element_rect(colour = "#FFFFBE", fill=NA, size=5))

hist_nne_wo_clim <- ggplot(data = surf_spots_nne, aes(x = sci_wo_climate)) +
  geom_histogram(breaks = c(0, 0.125, 0.25, 0.375, 0.5, 0.625, 0.75, 0.875, 1), fill = c("#d7191c", "#d7191c", "#fdae61", "#fdae61", "#a6d96a", "#a6d96a", "#1a9641", "#1a9641"), col = "black") +
  scale_y_continuous(limits = c(0, 60)) +
  geom_vline(xintercept = mean_priority_nne_wo_clim, linetype = 2) +
  labs(x = "SCI without Climate", y = "Number of breaks", title = "North/Northeast") +
  theme_minimal() +
  theme(text = element_text(size = 18), plot.background = element_rect(colour = "#FFBEBE", fill=NA, size=5))
hist_se_wo_clim <- ggplot(data = surf_spots_se, aes(x = sci_wo_climate)) +
  geom_histogram(breaks = c(0, 0.125, 0.25, 0.375, 0.5, 0.625, 0.75, 0.875, 1), fill = c("#d7191c", "#d7191c", "#fdae61", "#fdae61", "#a6d96a", "#a6d96a", "#1a9641", "#1a9641"), col = "black") +
  scale_y_continuous(limits = c(0, 60)) +
  geom_vline(xintercept = mean_priority_se_wo_clim, linetype = 2) +
  labs(x = "SCI without Climate", y = "Number of breaks", title = "Southeast") +
  theme_minimal() +
  theme(text = element_text(size = 18), plot.background = element_rect(colour = "#E8BEFF", fill=NA, size=5))
hist_s_wo_clim <- ggplot(data = surf_spots_s, aes(x = sci_wo_climate)) +
  geom_histogram(breaks = c(0, 0.125, 0.25, 0.375, 0.5, 0.625, 0.75, 0.875, 1), fill = c("#d7191c", "#d7191c", "#fdae61", "#fdae61", "#a6d96a", "#a6d96a", "#1a9641", "#1a9641"), col = "black") +
  scale_y_continuous(limits = c(0, 60)) +
  geom_vline(xintercept = mean_priority_s_wo_clim, linetype = 2) +
  labs(x = "SCI without Climate", y = "Number of breaks", title = "South") +
  theme_minimal() +
  theme(text = element_text(size = 18), plot.background = element_rect(colour = "#FFFFBE", fill=NA, size=5))
```

# Climate histograms

```{r}
hist_nne_carbon <- ggplot(data = surf_spots_nne, aes(x = normalized_carbon)) +
  geom_histogram(breaks = c(0, 0.2, 0.4, 0.6, 0.8, 1), fill = c("white", "#bae4b3", "#74c476", "#31a354", "#006d2c"), col = "black") +
  scale_y_continuous(limits = c(0, 200)) +
  #geom_vline(xintercept = mean_priority_s_w_clim, linetype = 2) +
  labs(x = "Normalized carbon storage", y = "Number of breaks", title = "North and Northeast")
hist_se_carbon <- ggplot(data = surf_spots_se, aes(x = normalized_carbon)) +
  geom_histogram(breaks = c(0, 0.2, 0.4, 0.6, 0.8, 1), fill = c("white", "#bae4b3", "#74c476", "#31a354", "#006d2c"), col = "black") +
  scale_y_continuous(limits = c(0, 200)) +
  #geom_vline(xintercept = mean_priority_s_w_clim, linetype = 2) +
  labs(x = "Normalized carbon storage", y = "Number of breaks", title = "Southeast")
hist_s_carbon <- ggplot(data = surf_spots_s, aes(x = normalized_carbon)) +
  geom_histogram(breaks = c(0, 0.2, 0.4, 0.6, 0.8, 1), fill = c("white", "#bae4b3", "#74c476", "#31a354", "#006d2c"), col = "black") +
  scale_y_continuous(limits = c(0, 200)) +
  #geom_vline(xintercept = mean_priority_s_w_clim, linetype = 2) +
  labs(x = "Normalized carbon storage", y = "Number of breaks", title = "South")

hist_nne_cp <- ggplot(data = surf_spots_nne, aes(x = normalized_cp)) +
  geom_histogram(breaks = c(0, 0.2, 0.4, 0.6, 0.8, 1), fill = c("#ffffb2", "#fecc5c", "#fd8d3c", "#f03b20", "#bd0026"), col = "black") +
  scale_y_continuous(limits = c(0, 115)) +
  #geom_vline(xintercept = mean_priority_s_w_clim, linetype = 2) +
  labs(x = "Normalized coastal protection", y = "Number of breaks", title = "North and Northeast")
hist_se_cp <- ggplot(data = surf_spots_se, aes(x = normalized_cp)) +
  geom_histogram(breaks = c(0, 0.2, 0.4, 0.6, 0.8, 1), fill = c("#ffffb2", "#fecc5c", "#fd8d3c", "#f03b20", "#bd0026"), col = "black") +
  scale_y_continuous(limits = c(0, 115)) +
  #geom_vline(xintercept = mean_priority_s_w_clim, linetype = 2) +
  labs(x = "Normalized coastal protection", y = "Number of breaks", title = "Southeast")
hist_s_cp <- ggplot(data = surf_spots_s, aes(x = normalized_cp)) +
  geom_histogram(breaks = c(0, 0.2, 0.4, 0.6, 0.8, 1), fill = c("#ffffb2", "#fecc5c", "#fd8d3c", "#f03b20", "#bd0026"), col = "black") +
  scale_y_continuous(limits = c(0, 115)) +
  #geom_vline(xintercept = mean_priority_s_w_clim, linetype = 2) +
  labs(x = "Normalized coastal protection", y = "Number of breaks", title = "South")
```


# Number of top spots in each state

```{r}
top_spots_by_state <- surf_spots %>% 
  group_by(state) %>% 
  summarize(count_10km = sum(sci_10km > 0.75), count_wo_clim = sum(sci_wo_climate > 0.75), count_5km = sum(sci_5km > 0.75), count_1km = sum(sci_1km > 0.75)) %>% 
  mutate(difference_5_10 = count_5km - count_10km) %>% 
  mutate(difference_1_10 = count_1km - count_10km) %>% 
  mutate(state = as.factor(state))

# order states north to south
top_spots_by_state <- top_spots_by_state %>% 
  arrange(factor(state, levels = c("Pará", "Maranhão", "Ceará", "Rio Grande do Norte", "Paraíba", "Pernambuco", "Alagoas", "Sergipe", "Bahia", "Espírito Santo", "Rio de Janeiro", "São Paulo", "Paraná", "Santa Catarina", "Rio Grande do Sul"))) %>% 
  mutate(state = factor(state, levels = c("Pará", "Maranhão", "Ceará", "Rio Grande do Norte", "Paraíba", "Pernambuco", "Alagoas", "Sergipe", "Bahia", "Espírito Santo", "Rio de Janeiro", "São Paulo", "Paraná", "Santa Catarina", "Rio Grande do Sul")))

# add regions to top states
top_spots_by_state$region <- c("North/northeast", "North/northeast", "North/northeast", "North/northeast", "North/northeast", "North/northeast", "North/northeast", "North/northeast", "North/northeast", "Southeast", "Southeast", "Southeast", "South", "South", "South")

states_w_clim <- ggplot(top_spots_by_state, aes(x = state, y = count_10km, fill = region)) +
  geom_col(col = "black") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
  scale_y_continuous(limits = c(0, 22)) +
  scale_fill_manual(values = c("#FFBEBE", "#FFFFBE", "#E8BEFF")) +
  theme(legend.position = "none") +
  labs(x = "State", y = "Number of top breaks")

states_wo_clim <- ggplot(top_spots_by_state, aes(x = state, y = count_wo_clim, fill = region)) +
  geom_col(col = "black") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
  scale_y_continuous(limits = c(0, 22)) +
  scale_fill_manual(values = c("#FFBEBE", "#FFFFBE", "#E8BEFF")) +
  theme(legend.position = "none") +
  labs(x = "State", y = "Number of top breaks")

states_5km <- ggplot(top_spots_by_state, aes(x = state, y = difference_5_10, fill = region)) +
  geom_col(col = "black") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
  scale_y_continuous(limits = c(-15, 5)) +
  scale_fill_manual(values = c("#FFBEBE", "#FFFFBE", "#E8BEFF")) +
  theme(legend.position = "none") +
  labs(x = "State", y = "Number of top breaks")

states_1km <- ggplot(top_spots_by_state, aes(x = state, y = difference_1_10, fill = region)) +
  geom_col(col = "black") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
  scale_y_continuous(limits = c(-15, 5)) +
  scale_fill_manual(values = c("#FFBEBE", "#FFFFBE", "#E8BEFF")) +
  theme(legend.position = "none") +
  labs(x = "State", y = "Number of top breaks")
```

# Join into figures

```{r}
figure1 <- plot_grid(hist_wo_clim, hist_w_clim, states_wo_clim, states_w_clim, labels = "AUTO", ncol = 2)
figure1

# add mean line and change x axis label on hist_w_clim for sensitivity analysis figure
hist_w_clim_sens <- hist_w_clim +
  labs(x = "SCI with Climate (10 km)") +
  geom_vline(xintercept = mean_priority_10km_wo_clim, linetype = 2)

# increase font size for figure 2
# hist_w_clim <- hist_w_clim +
#   theme(text = element_text(size = 20))
# hist_5km <- hist_5km +
#   theme(text = element_text(size = 20))
# hist_1km <- hist_1km +
#   theme(text = element_text(size = 20))

figure2_top_row <- plot_grid(hist_w_clim_sens, hist_5km, hist_1km, labels = "AUTO", nrow = 1)
figure2_bottom_row <- plot_grid(states_5km, states_1km, labels = c("D", "E"), nrow = 1)
figure2 <- plot_grid(figure2_top_row, figure2_bottom_row, labels = "", nrow = 2)

figure2
```

```{r}
sci_report_figure <- plot_grid(hist_w_clim, states_w_clim, ncol = 1, labels = "AUTO")
```

# Differences Histogram

```{r}
sci_diff <- surf_spots %>% 
  filter(difference < 0)

sci_clim_diff <- surf_spots %>% 
  filter(difference > 0)

sci_diff_sum <- sci_diff %>% 
  group_by(region) %>% 
  summarize(sci_count = n())

sci_clim_diff_sum <- sci_clim_diff %>% 
  group_by(region) %>% 
  summarize(sci_clim_count = n())

x <- c("Norte", "Nordeste", "Sudeste", "Sul")

diff <- sci_diff_sum %>% 
  left_join(sci_clim_diff_sum, by = "region", keep = FALSE) %>% 
  slice(match(x, region))

ggplot(data = diff) +
  geom_col(aes(x = region, y = sci_count))
  geom_col(aes(x = region, y = sci_clim_count))
```

# Region Counts

```{r}
surf_spots_nne_subset <- surf_spots_nne %>% 
  select(id, region, sci_10km) %>% 
  mutate(rank = case_when(
    sci_10km > 0.75 ~ "High Priority",
    sci_10km <= 0.75 & sci_10km > 0.5 ~ "Medium Priority",
    sci_10km <= 0.5 & sci_10km > 0.25 ~ "Low Priority",
    sci_10km <= 0.25 ~ "Very Low Priority"
  )) %>% 
  group_by(rank) %>% 
  summarize(count = n())

surf_spots_se_subset <- surf_spots_se %>% 
  select(id, region, sci_10km) %>% 
  mutate(rank = case_when(
    sci_10km > 0.75 ~ "High Priority",
    sci_10km <= 0.75 & sci_10km > 0.5 ~ "Medium Priority",
    sci_10km <= 0.5 & sci_10km > 0.25 ~ "Low Priority",
    sci_10km <= 0.25 ~ "Very Low Priority"
  )) %>% 
  group_by(rank) %>% 
  summarize(count = n())

surf_spots_s_subset <- surf_spots_s %>% 
  select(id, region, sci_10km) %>% 
  mutate(rank = case_when(
    sci_10km > 0.75 ~ "High Priority",
    sci_10km <= 0.75 & sci_10km > 0.5 ~ "Medium Priority",
    sci_10km <= 0.5 & sci_10km > 0.25 ~ "Low Priority",
    sci_10km <= 0.25 ~ "Very Low Priority"
  )) %>% 
  group_by(rank) %>% 
  summarize(count = n())
```

## Combine SCI data with Sensitivity Analysis

```{r}
sci_data <- read_csv(here("all_data.csv"))

sci_sa <- left_join(sci_data, sci_w_climate_5km,
                   by = "id")

all_data_sa <- left_join(sci_sa, sci_w_climate_1km,
                         by = "id")
```

```{r}
# export
write_csv(all_data_sa, file = "all_data_sa.csv")
```




