# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2023-05-26 15:12:06
"""
import arcpy
from sys import argv

def BiodiversitySubindex(new_all_surf_spots_biodiversity="new_all_surf_spots_biodiversity", normalized_biodiversity_1_csv="normalized_biodiversity (1).csv"):  # BiodiversitySubindex

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Model Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"G:\Brazil_SCI\Brazil_SCI.gdb", workspace=r"G:\Brazil_SCI\Brazil_SCI.gdb"):

        # Process: Join Field (Join Field) (management)
        Biodiversity_Subindex = arcpy.management.JoinField(in_data=new_all_surf_spots_biodiversity, in_field="id", join_table=normalized_biodiversity_1_csv, join_field="id", fields=["normalized_terr_rich", "normalized_mar_rich", "normalized_marine_eco", "normalized_ocean_pa", "normalized_terr_pa", "normalized_tree_cover", "added_biodiversity", "biodiversity_subindex"])[0]

        return Biodiversity_Subindex

if __name__ == '__main__':
    BiodiversitySubindex(*argv[1:])
