# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2023-05-26 15:13:18
"""
import arcpy
from sys import argv

def SocialSubindex(new_all_surf_spots_social="new_all_surf_spots_social", normalized_social_1_csv="normalized_social (1).csv"):  # SocialSubindex

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False


    # Process: Join Field (Join Field) (management)
    Social_SubIndex = arcpy.management.JoinField(in_data=new_all_surf_spots_social, in_field="id", join_table=normalized_social_1_csv, join_field="id", fields=["normalized_employment", "normalized_hotels", "normalized_airports", "social_added", "social_subindex"])[0]

    return Social_SubIndex

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"G:\Brazil_SCI\Brazil_SCI.gdb", workspace=r"G:\Brazil_SCI\Brazil_SCI.gdb"):
        SocialSubindex(*argv[1:])
