# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2023-05-26 15:12:34
"""
import arcpy
from sys import argv

def SurfSubindex(new_all_surf_spots_surf="new_all_surf_spots_surf", normalized_surf_1_csv="normalized_surf (1).csv"):  # SurfSubindex

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False


    # Process: Surf Subindex Join Field (Join Field) (management)
    Surf_Subindex = arcpy.management.JoinField(in_data=new_all_surf_spots_surf, in_field="id", join_table=normalized_surf_1_csv, join_field="id", fields=["normalized_clusters", "normalized_direction", "normalized_frequency", "normalized_experience", "normalized_quality", "added_surf", "surf_subindex"])[0]

    return Surf_Subindex

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"G:\Brazil_SCI\Brazil_SCI.gdb", workspace=r"G:\Brazil_SCI\Brazil_SCI.gdb"):
        SurfSubindex(*argv[1:])
